Oleg_Sobol_homework27_Playwright2
eugene-okulik/sobolev_aleh pull request #28
Opened 2024-11-07 22:13 UTC by OlegSobol69

2024-11-08 09:08 UTC, eugene-okulik requested changes
Кроме первого задания, всё отлично.

2024-11-08 09:08 UTC, eugene-okulik commented on homework/oleg_sobol/homework_27_playwright_2/homework_27.py
> +    expect(text).to_be_visible()
Если выполнить то, что написано в задании, то видно, что тест делает не то, что должен. И результат этого теста будет Failed.
> проверяет, что на страние в секции "You selected" написано "Ok"

2024-11-08 16:35 UTC, OlegSobol69 commented on homework/oleg_sobol/homework_27_playwright_2/homework_27.py
> +    expect(text).to_be_visible()
исправил
и добавил обработку алерта (потому что вариант предыдущий начал нажимать Cancel )

2024-11-09 08:41 UTC, eugene-okulik approved these changes

2024-11-09 08:41 UTC, eugene-okulik commented on homework/oleg_sobol/homework_27_playwright_2/homework_27.py
> +    page.on("dialog", handle_dialog)
Достаточно было просто перенести сюда (до клика) ту строчку `page.on("dialog", lambda dialog: dialog.accept())`, которая у тебя была. А для надежности, этот `page.on` вообще можно вставлять до открытия страницы.

2024-11-09 08:41 UTC, merged

2024-11-09 13:27 UTC, OlegSobol69 commented on homework/oleg_sobol/homework_27_playwright_2/homework_27.py
> +    page.on("dialog", handle_dialog)
понял 
проверил - работает 
нажимает "Ок"
спасибо)